### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by wattlebird** [wattlebird/chii-frontend#1]
- [x] GraphQL error handling
- [x] Sort button is not correct
- [x] Header and about page
- [x] Redirecting non-exist urls
- [x] CI CD pipeline to release on release branch
